version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/workflow-templates"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Europe/Oslo"
      day: "monday"