# ╔═╗╔═╗╔╦╗╔═╗╦  ╔═╗       ╔╗╔╔═╗╔╦╗  ╦═╗╔═╗╔═╗╔╦╗╦ ╦  ╔═╗╔═╗╦═╗  ╦ ╦╔═╗╔═╗
# ╚═╗╠═╣║║║╠═╝║  ║╣   ───  ║║║║ ║ ║   ╠╦╝║╣ ╠═╣ ║║╚╦╝  ╠╣ ║ ║╠╦╝  ║ ║╚═╗║╣
# ╚═╝╩ ╩╩ ╩╩  ╩═╝╚═╝       ╝╚╝╚═╝ ╩   ╩╚═╚═╝╩ ╩═╩╝ ╩   ╚  ╚═╝╩╚═  ╚═╝╚═╝╚═╝
# TODO: This file comes from entur/.github/workflows/cd-both.yaml
#       Adopt to your needs, this file is yours now.
name: CD
on:
  push:
    branches:
      - $default-branch

jobs:
  docker-build:
    uses: entur/gha-docker/.github/workflows/build.yml@v1

  docker-push:
    needs: docker-build
    uses: entur/gha-docker/.github/workflows/push.yml@v1
    with:
      environment: dev

  terraform-apply:
    uses: entur/gha-terraform/.github/workflows/force-apply.yml@v1
    with:
      environment: dev

  helm-deploy:
    needs: [docker-push, terraform-apply]
    uses: entur/gha-helm/.github/workflows/deploy.yml@v1
    with:
      image: ${{ needs.docker-push.outputs.image_name }}:${{ needs.docker-push.outputs.image_tag}}
      environment: dev
