# ╔═╗╔═╗╔╦╗╔═╗╦  ╔═╗       ╔╗╔╔═╗╔╦╗  ╦═╗╔═╗╔═╗╔╦╗╦ ╦  ╔═╗╔═╗╦═╗  ╦ ╦╔═╗╔═╗
# ╚═╗╠═╣║║║╠═╝║  ║╣   ───  ║║║║ ║ ║   ╠╦╝║╣ ╠═╣ ║║╚╦╝  ╠╣ ║ ║╠╦╝  ║ ║╚═╗║╣
# ╚═╝╩ ╩╩ ╩╩  ╩═╝╚═╝       ╝╚╝╚═╝ ╩   ╩╚═╚═╝╩ ╩═╩╝ ╩   ╚  ╚═╝╩╚═  ╚═╝╚═╝╚═╝
# TODO: This file comes from entur/.github/workflows/ci-docker.yaml
#       You may not need terraform, or use a different Dockerfile
#       Simply delete what you do not need. This file is yours now.
name: CI
on:
  pull_request:
    branches:
      - $default-branch
jobs:
  docker-lint:
    uses: entur/gha-docker/.github/workflows/lint.yml@v1
  helm-lint:
    uses: entur/gha-helm/.github/workflows/lint.yml@v1
    with:
      environment: dev
  terraform-lint:
    uses: entur/gha-terraform/.github/workflows/lint.yml@v1
  terraform-plan:
    uses: entur/gha-terraform/.github/workflows/plan.yml@v1
    with:
      environment: dev
