#  ____   _                            _
# / ___| | |__    __ _  _ __  ___   __| |
# \___ \ | '_ \  / _` || '__|/ _ \ / _` |
#  ___) || | | || (_| || |  |  __/| (_| |
# |____/ |_| |_| \__,_||_|   \___| \__,_|
# __        __            _      __  _
# \ \      / /___   _ __ | | __ / _|| |  ___ __      __ ___
#  \ \ /\ / // _ \ | '__|| |/ /| |_ | | / _ \\ \ /\ / // __|
#   \ V  V /| (_) || |   |   < |  _|| || (_) |\ V  V / \__ \
#    \_/\_/  \___/ |_|   |_|\_\|_|  |_| \___/  \_/\_/  |___/
#        ____                _                 _      _         _
# __/\__|  _ \   ___    ___ | | __ ___  _ __  | |    (_) _ __  | |_
# \    /| | | | / _ \  / __|| |/ // _ \| '__| | |    | || '_ \ | __|
# /_  _\| |_| || (_) || (__ |   <|  __/| |    | |___ | || | | || |_
#   \/  |____/  \___/  \___||_|\_\\___||_|    |_____||_||_| |_| \__|
#
# TODO: This file comes from entur/.github/workflows/docker-lint.yml
#       Adopt to your needs, this file is yours now.
#
# Reusable Workflows used:
# * Docker Lint
#   * Readme <https://github.com/entur/gha-docker/blob/main/README-lint.md>
#   * Owner: Team Plattform
#   * Slack: #Talk-plattform
#
name: Docker Lint
on:
  push: # on push to any branch
     paths: # only run on changes to the following files
      - Dockerfile
  pull_request: # on pull request to any branch
    paths:
      - Dockerfile

jobs:
  docker-lint:
    name: Docker Lint
    uses: entur/gha-docker/.github/workflows/lint.yml@v1
    with:
      dockerfile: Dockerfile
      # ignore: DL3008 # Example ignore: Ignore warning about pinning versions https://github.com/hadolint/hadolint/wiki/DL3008
