name: Push
on:
  push:
    branches:
      - main

jobs:
  gradle-build: # https://github.com/actions/starter-workflows/blob/main/ci/gradle.yml
    if: ${{ github.triggering_actor != 'dependabot[bot]' }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # v4.1.0
      - name: Build with Gradle Wrapper
        run: ./gradlew build
        env:
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          ARTIFACTORY_APIKEY: ${{ secrets.ARTIFACTORY_APIKEY }}
      - name: Archive Build Artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: build/libs
          retention-days: 1
          overwrite: true
  docker-build:
    if: ${{ github.triggering_actor != 'dependabot[bot]' }}
    needs: gradle-build
    uses: entur/gha-docker/.github/workflows/build.yml@v1
    with:
      build_artifact_name: app
      build_artifact_path: build/libs
  docker-push:
    if: ${{ github.triggering_actor != 'dependabot[bot]' }}
    needs: docker-build
    uses: entur/gha-docker/.github/workflows/push.yml@v1
